#!/usr/bin/env python3
"""
img2c.py - Convert an image into an LVGL 8.x image descriptor (.c) for embedding
in flash, so the JSON UI can reference it by name via the image registry
(see UiContext::registerImage + "bg_img"/"src" in the schema).

Output format: RGB565 TRUE_COLOR, little-endian (matches LV_COLOR_DEPTH=16 and
LV_COLOR_16_SWAP=0 in include/lv_conf.h). One image -> one .c file holding a
`static const uint8_t <name>_map[]` plus a `const lv_img_dsc_t <name>` symbol.

Requires Pillow:  pip install pillow

Examples
--------
# Whole image, resized to the panel resolution:
python utils/img2c.py src/assets/images/background.png -W 800 -H 480

# Crop the inner panel out of the 1264x842 render, then resize to 800x480
# (this is how src/assets/images/background_img.c was generated):
python utils/img2c.py src/assets/images/background.png \
    --crop 109,84,1162,724 -W 800 -H 480 \
    -o src/assets/images/background_img.c --name background_img

After generating, declare the symbol in a header (see src/assets/images/Images.h)
and register it once at startup:  g_ui.registerImage("background", &background_img);
"""
import argparse
import os
import re
import sys


def sanitize(name: str) -> str:
    """Make a valid C identifier from a string."""
    name = re.sub(r"[^0-9A-Za-z_]", "_", name)
    if name and name[0].isdigit():
        name = "_" + name
    return name or "image"


def main() -> int:
    p = argparse.ArgumentParser(
        description="Convert an image to an LVGL RGB565 .c image descriptor.")
    p.add_argument("input", help="source image (png/jpg/...)")
    p.add_argument("-o", "--output",
                   help="output .c path (default: <input dir>/<name>.c)")
    p.add_argument("--name",
                   help="C symbol name (default: derived from the input filename)")
    p.add_argument("-W", "--width", type=int,
                   help="resize width in px (keep aspect if only one of W/H given)")
    p.add_argument("-H", "--height", type=int,
                   help="resize height in px")
    p.add_argument("--crop", metavar="L,T,R,B",
                   help="crop box before resizing, e.g. 109,84,1162,724")
    p.add_argument("--swap", action="store_true",
                   help="store bytes big-endian (use only if LV_COLOR_16_SWAP=1)")
    args = p.parse_args()

    try:
        from PIL import Image
    except ImportError:
        print("error: Pillow is required ->  pip install pillow", file=sys.stderr)
        return 1

    try:
        import numpy as np
    except ImportError:
        np = None  # pure-python fallback below

    if not os.path.isfile(args.input):
        print(f"error: no such file: {args.input}", file=sys.stderr)
        return 1

    name = sanitize(args.name or os.path.splitext(os.path.basename(args.input))[0])
    out = args.output or os.path.join(os.path.dirname(args.input), name + ".c")

    im = Image.open(args.input).convert("RGB")

    if args.crop:
        try:
            l, t, r, b = (int(v) for v in args.crop.split(","))
        except ValueError:
            print("error: --crop must be L,T,R,B integers", file=sys.stderr)
            return 1
        im = im.crop((l, t, r, b))

    w, h = im.size
    if args.width and args.height:
        w, h = args.width, args.height
    elif args.width:
        h = round(h * args.width / w); w = args.width
    elif args.height:
        w = round(w * args.height / h); h = args.height
    if (w, h) != im.size:
        im = im.resize((w, h), Image.LANCZOS)

    # RGB888 -> RGB565
    if np is not None:
        a = np.asarray(im, dtype=np.uint16)
        r = (a[:, :, 0] >> 3) & 0x1F
        g = (a[:, :, 1] >> 2) & 0x3F
        bl = (a[:, :, 2] >> 3) & 0x1F
        val = ((r << 11) | (g << 5) | bl).flatten()
        lo = (val & 0xFF).astype(np.uint8)
        hi = (val >> 8).astype(np.uint8)
        inter = np.empty(val.size * 2, dtype=np.uint8)
        if args.swap:
            inter[0::2], inter[1::2] = hi, lo
        else:
            inter[0::2], inter[1::2] = lo, hi
        data = inter.tolist()
    else:
        data = []
        for (rr, gg, bb) in im.getdata():
            v = ((rr >> 3) << 11) | ((gg >> 2) << 5) | (bb >> 3)
            hi, lo = (v >> 8) & 0xFF, v & 0xFF
            data += ([hi, lo] if args.swap else [lo, hi])

    os.makedirs(os.path.dirname(out) or ".", exist_ok=True)
    with open(out, "w", encoding="ascii") as f:
        f.write(f"/* Auto-generated by utils/img2c.py from "
                f"{os.path.basename(args.input)} ({w}x{h}, RGB565 true color). */\n")
        f.write("#include <lvgl.h>\n\n")
        f.write("#ifndef LV_ATTRIBUTE_MEM_ALIGN\n#define LV_ATTRIBUTE_MEM_ALIGN\n#endif\n\n")
        f.write(f"static const LV_ATTRIBUTE_MEM_ALIGN uint8_t {name}_map[] = {{\n")
        line = []
        for i, byte in enumerate(data):
            line.append("0x%02x," % byte)
            if (i + 1) % 32 == 0:
                f.write("".join(line) + "\n")
                line = []
        if line:
            f.write("".join(line) + "\n")
        f.write("};\n\n")
        f.write(f"const lv_img_dsc_t {name} = {{\n")
        f.write("  .header.cf = LV_IMG_CF_TRUE_COLOR,\n")
        f.write("  .header.always_zero = 0,\n")
        f.write("  .header.reserved = 0,\n")
        f.write(f"  .header.w = {w},\n")
        f.write(f"  .header.h = {h},\n")
        f.write(f"  .data_size = {w} * {h} * LV_COLOR_SIZE / 8,\n")
        f.write(f"  .data = {name}_map,\n")
        f.write("};\n")

    print(f"wrote {out}  ({w}x{h}, {len(data)} bytes, symbol '{name}')")
    print(f"  add to a header:  extern const lv_img_dsc_t {name};")
    print(f"  register at boot: g_ui.registerImage(\"{name}\", &{name});")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
